### ISSUE TITLE
database : Customer : url must absolutely be unique!

### ISSUE THREAD

**Issue by wazoox** [ChyroBroadcast/ftp-adm-frontend#10]
We identify incoming users by the VHost they're coming from, so url must be unique.

**Comment by ddegorre-harmonicinc** [comment]
They are ! 

src/Qlowd/FtpadmBundle/Resources/config/doctrine/Customer.orm.yml : 
Qlowd\FtpadmBundle\Entity\Customer:
    type: entity
    table: Customer
    uniqueConstraints:
        name:
            columns:
                - name
                - url

I take maybe 2 hours to understand it with doctrine :/

Use https://github.com/ChyroBroadcast/ftp-adm-frontend/wiki/Update-SQL  to update Schema...
